var CONSTANTS = {}

CONSTANTS.SPEED = 3
CONSTANTS.JUMP_SPEED = 2.5
CONSTANTS.WIDTH = 640
CONSTANTS.HEIGHT = 480
CONSTANTS.SIZE = 16
CONSTANTS.TERRAIN_HEIGHT = 40
CONSTANTS.MAP_SIZE = 100
CONSTANTS.SKY_COLOR = "rgb(87, 238, 255)"
CONSTANTS.PLAYER_COLOR = "rgb(255, 0, 0)"
CONSTANTS.PLAYER_HEIGHT = CONSTANTS.SIZE * 2
CONSTANTS.GRAVITY = 0.15
CONSTANTS.TERMINAL_VELOCITY = 5

module.exports = CONSTANTS
